name: launch_spacex
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  searchbar_animation: ^0.0.4
  meta: ^1.0.9
  easy_localization: ^3.0.3
  # firebase dependencies
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  email_validator: ^2.1.17
  firebase_messaging: ^14.6.7
  get_it: ^7.6.4

  # Notification
#  awesome_notifications: 0.7.4+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
